image: node:latest

test:
  script:
  - yarn
  - yarn lint
  - yarn test
  - yarn build
  artifacts:
    paths:
    - dist

deploy:
  stage: deploy
  script:
  - apt-get update && apt-get install -y rsync
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$DEPLOY_SSH_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - rsync -av --delete dist/ ukuvota-deploy@yuca.yunity.org:/var/www/ukuvota/www/
  environment:
    name: production
    url: https://ukuvota.world
  only:
  - master
