name: ukuvota
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.2
  flutter_markdown: ^0.6.20
  flutter_quill: ^9.3.0
  url_launcher: ^6.2.6
  flutter_keyboard_visibility: ^6.0.0
  device_info_plus: ^9.1.2
  super_clipboard: ^0.8.5
  go_router: ^13.2.4
  uuid: ^4.4.0
  timezone: ^0.9.3
  shared_preferences: ^2.2.3
  vsc_quill_delta_to_html: ^1.0.4
  flutter_widget_from_html: ^0.9.1
  chewie: ^1.8.1
  flutter_timezone_plus: ^1.1.0
  firebase_database: ^10.5.4
  firebase_storage: ^11.7.4
  provider: ^6.1.2
  path_provider: ^2.1.3
  http: ^1.2.1
  qr_flutter: ^4.1.0
  firebase_core: ^2.30.1
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/emojis/angry.svg
    - assets/emojis/happy.svg
    - assets/emojis/loving.svg
    - assets/emojis/neutral.svg
    - assets/emojis/rage.svg
    - assets/emojis/sad.svg
    - assets/emojis/smiling.svg
    - assets/content/de/
    - assets/content/en/
    - assets/content/es/
    - assets/content/it/

#   - images/a_dot_ham.jpeg
