name: ukuvota
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_markdown: ^0.6.20

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/content/de/
    - assets/content/en/
    - assets/content/es/
    - assets/content/it/

#   - images/a_dot_ham.jpeg
