import { f as createComponent, r as renderTemplate, m as maybeRenderHead, u as unescapeHTML } from './astro_fCW-vF1L.mjs';
import 'kleur/colors';
import 'clsx';

const html = "<h1 id=\"privacy-policy-for-evotico\">Privacy Policy for Evotico</h1>\n<p><strong>Last updated: 2023-09-09</strong></p>\n<h2 id=\"1-introduction\">1. Introduction</h2>\n<p>Welcome to Evotico. We are committed to protecting your personal information and your right to privacy. If you have any questions or concerns about this privacy notice or our practices with regard to your personal information, please contact us.</p>\n<p>This privacy notice describes how we might use your information if you use our score voting tool. It applies to all users of our tool.</p>\n<h2 id=\"2-information-we-collect\">2. Information We Collect</h2>\n<p>Our tool allows you to input data to help you find decisions. The data you input is saved on our server in a LevelDB database.</p>\n<h2 id=\"3-how-we-use-your-information\">3. How We Use Your Information</h2>\n<p>We use the data you provide to operate our tool and enable the score voting functionality. The data is stored for the purpose of providing you with the tool’s features and is not used for any other purposes.</p>\n<h2 id=\"4-data-security\">4. Data Security</h2>\n<p>We have implemented appropriate technical and organizational security measures designed to protect the security of any personal information we process. However, despite our safeguards and efforts to secure your information, no electronic transmission over the Internet or information storage technology can be guaranteed to be 100% secure, so we cannot promise or guarantee that hackers, cybercriminals, or other unauthorized third parties will not be able to defeat our security, and improperly collect, access, steal, or modify your information.</p>\n<h2 id=\"5-data-retention\">5. Data Retention</h2>\n<p>We retain the data you input into our tool indefinitely. As of now, we do not offer a way to delete data once it has been inputted into our tool. Users should be cautious and considerate of the information they input, given its indefinite storage.</p>\n<h2 id=\"6-limitation-of-liability\">6. Limitation of Liability</h2>\n<p>While we strive to protect the data you input into our tool, Evotico is not responsible for any loss of data. We recommend that users regularly back up their data to prevent any potential loss.</p>\n<h2 id=\"7-updates-to-this-privacy-notice\">7. Updates to this Privacy Notice</h2>\n<p>We may update this privacy notice from time to time. The updated version will be indicated by an updated “Revised” date and the updated version will be effective as soon as it is accessible.</p>\n<h2 id=\"8-how-to-contact-us\">8. How to Contact Us</h2>\n<p>If you have questions or comments about this privacy notice, you may contact us.</p>";

				const frontmatter = {};
				const file = "/home/wao/Meteor/Workspace/Nao/evotico/src/content/en/PrivacyPolicy.md";
				const url = undefined;
				function rawContent() {
					return "# Privacy Policy for Evotico\n\n**Last updated: 2023-09-09**\n\n## 1. Introduction\n\nWelcome to Evotico. We are committed to protecting your personal information and your right to privacy. If you have any questions or concerns about this privacy notice or our practices with regard to your personal information, please contact us.\n\nThis privacy notice describes how we might use your information if you use our score voting tool. It applies to all users of our tool.\n\n## 2. Information We Collect\n\nOur tool allows you to input data to help you find decisions. The data you input is saved on our server in a LevelDB database.\n\n## 3. How We Use Your Information\n\nWe use the data you provide to operate our tool and enable the score voting functionality. The data is stored for the purpose of providing you with the tool's features and is not used for any other purposes.\n\n## 4. Data Security\n\nWe have implemented appropriate technical and organizational security measures designed to protect the security of any personal information we process. However, despite our safeguards and efforts to secure your information, no electronic transmission over the Internet or information storage technology can be guaranteed to be 100% secure, so we cannot promise or guarantee that hackers, cybercriminals, or other unauthorized third parties will not be able to defeat our security, and improperly collect, access, steal, or modify your information.\n\n## 5. Data Retention\n\nWe retain the data you input into our tool indefinitely. As of now, we do not offer a way to delete data once it has been inputted into our tool. Users should be cautious and considerate of the information they input, given its indefinite storage.\n\n## 6. Limitation of Liability\n\nWhile we strive to protect the data you input into our tool, Evotico is not responsible for any loss of data. We recommend that users regularly back up their data to prevent any potential loss.\n\n## 7. Updates to this Privacy Notice\n\nWe may update this privacy notice from time to time. The updated version will be indicated by an updated \"Revised\" date and the updated version will be effective as soon as it is accessible.\n\n## 8. How to Contact Us\n\nIf you have questions or comments about this privacy notice, you may contact us.\n";
				}
				function compiledContent() {
					return html;
				}
				function getHeadings() {
					return [{"depth":1,"slug":"privacy-policy-for-evotico","text":"Privacy Policy for Evotico"},{"depth":2,"slug":"1-introduction","text":"1. Introduction"},{"depth":2,"slug":"2-information-we-collect","text":"2. Information We Collect"},{"depth":2,"slug":"3-how-we-use-your-information","text":"3. How We Use Your Information"},{"depth":2,"slug":"4-data-security","text":"4. Data Security"},{"depth":2,"slug":"5-data-retention","text":"5. Data Retention"},{"depth":2,"slug":"6-limitation-of-liability","text":"6. Limitation of Liability"},{"depth":2,"slug":"7-updates-to-this-privacy-notice","text":"7. Updates to this Privacy Notice"},{"depth":2,"slug":"8-how-to-contact-us","text":"8. How to Contact Us"}];
				}

				const Content = createComponent((result, _props, slots) => {
					const { layout, ...content } = frontmatter;
					content.file = file;
					content.url = url;

					return renderTemplate`${maybeRenderHead()}${unescapeHTML(html)}`;
				});

export { Content, compiledContent, Content as default, file, frontmatter, getHeadings, rawContent, url };
