name: Android Build Release

on:
  push:
    branches:
      - main
    tags:
      - '*'

env:
  FLUTTER_VERSION: '3.19.6'
  IS_PRERELEASE: ${{ startsWith(github.ref, 'refs/tags/') && 'false' || 'true' }}
  RELEASE_TAG: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || 'latest' }}

jobs:
  cancel:
    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    steps:
    - uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}

  android:
    needs: cancel
    name: Build APK
    runs-on: ubuntu-latest
    env:
      FLUTTER_KEY_ALIAS: ${{ secrets.FLUTTER_KEY_ALIAS }}
      FLUTTER_KEY_PASSWORD: ${{ secrets.FLUTTER_KEY_PASSWORD }}
      FLUTTER_STORE_PASSWORD: ${{ secrets.FLUTTER_STORE_PASSWORD }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - uses: actions/cache@v2
      with:
        path: |
          ~/.pub-cache
          ~/.flutter
        key: ${{ runner.os }}-flutter-${{ env.FLUTTER_VERSION }}-${{ hashFiles('**/pubspec.yaml') }}
        restore-keys: ${{ runner.os }}-flutter-${{ env.FLUTTER_VERSION }}-
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
    - run: npm install -g firebase-tools
    - run: |
        echo ${{ secrets.FIREBASE_TOKEN }} | firebase login:ci
        firebase use ${{ secrets.FIREBASE_PROJECT_ID }}
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    - run: flutter pub get
    - run: flutter gen-l10n
    - run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" > android/app/google-services.json
    - run: echo "${{ secrets.FLUTTER_STORE_FILE }}" | base64 -d > android/app/release-key.jks
    - run: flutter build apk --release
    - run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/Ukuvota.apk
    - uses: actions/upload-artifact@v2
      with:
        name: apk-artifacts
        path: build/app/outputs/flutter-apk/Ukuvota.apk

  release:
    name: Release Builds
    needs: android
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v2
      with:
        name: apk-artifacts
        path: build/app/outputs/flutter-apk/
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ env.RELEASE_TAG }}"
        prerelease: "${{ env.IS_PRERELEASE }}"
        title: "${{ env.RELEASE_TAG }}"
        files: build/app/outputs/flutter-apk/Ukuvota.apk
